### ISSUE TITLE
1000 Genome Tree script not replicable because of msprime.RateMap 

### ISSUE THREAD

**Issue by xinyli** [awohns/tsdate_paper#25]
I am trying to replicate the script to generate ARG trees for a subset of 1000G data. However, it is giving me the error message: 
AttributeError: module 'msprime' has no attribute 'RateMap'

My msprime version is 0.7.4.  How should I sole this ?

**Comment by awohns** [comment]
Hi @xinyli! If you run `python -m pip install -r requirements.txt`, the alpha version of `msprime` which supports RateMaps should install. Let me know if that works for you.

**Comment by xinyli** [comment]
It is giving me error: 
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-to6zfqok/setup.py'

**Comment by awohns** [comment]
Thanks for spotting this @xinyli, I've updated the requirements.txt so it should work now.

The problem was that we had to install the github verison of `tskit` (and should have specified the python subdirectory), but now `tskit` version 0.3.5 is released I just specified that instead.

Please feel free to close the issue if this solves the problem

**Comment by awohns** [comment]
Hi @xinyli, I'm going to close the issue since it seems like the install problem is solved. Let me know if you run into further issues
